name: Severyn Kozak
url: http://sevko.io
description: The personal site and blog of Severyn Kozak.
permalink: /blog/:title
markdown: kramdown
lsi: true
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"

sass:
    style: :compressed
