name: Severyn Kozak
permalink: /blog/:title
markdown: kramdown
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"

sass:
    style: :compressed
