name: Severyn Kozak
url: http://sevko.io
description: Severyn Kozak's personal site and blog.
permalink: /blog/:title
markdown: kramdown
lsi: true
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            toc: true

sass:
    style: :compressed
